import { Resend } from 'resend';

interface EmailParams {
  submission: {
    id: string;
    totalAmount: number;
  };
  requester: {
    payableTo: string;
    email: string;
    phone?: string;
    address: string;
    dateCheckNeeded: string;
  };
  receipts: Array<{
    description: string;
    amount: number;
    budgetAccount: string;
  }>;
  pdfBuffer: Uint8Array;
  notificationEmail: string;
  resendApiKey: string;
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount);
}

function generateEmailHTML(
  submission: EmailParams['submission'],
  requester: EmailParams['requester'],
  receipts: EmailParams['receipts']
): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; }
        .header { background: #4F46E5; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { padding: 24px; background: #fff; border: 1px solid #e5e7eb; border-top: none; }
        .receipt-table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        .receipt-table th, .receipt-table td { border: 1px solid #e5e7eb; padding: 10px; text-align: left; }
        .receipt-table th { background: #f9fafb; font-weight: 600; }
        .total { font-size: 18px; font-weight: bold; text-align: right; margin-top: 16px; }
        .info-section { background: #f9fafb; padding: 16px; border-radius: 8px; margin-bottom: 16px; }
        .footer { text-align: center; padding: 16px; color: #6b7280; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 style="margin: 0; font-size: 24px;">New Check Request</h1>
      </div>
      <div class="content">
        <div class="info-section">
          <p style="margin: 0;"><strong>Payable to:</strong> ${requester.payableTo}</p>
          <p style="margin: 4px 0 0;"><strong>Email:</strong> ${requester.email}</p>
          ${requester.phone ? `<p style="margin: 4px 0 0;"><strong>Phone:</strong> ${requester.phone}</p>` : ''}
          <p style="margin: 4px 0 0;"><strong>Address:</strong> ${requester.address}</p>
          <p style="margin: 4px 0 0;"><strong>Check Needed By:</strong> ${requester.dateCheckNeeded}</p>
          <p style="margin: 4px 0 0;"><strong>Reference ID:</strong> ${submission.id}</p>
        </div>

        <h2 style="font-size: 18px; margin-bottom: 8px;">Expense Summary</h2>
        <table class="receipt-table">
          <thead>
            <tr>
              <th>Description</th>
              <th>Budget Account</th>
              <th style="text-align: right;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${receipts
              .map(
                (r) => `
              <tr>
                <td>${r.description}</td>
                <td>${r.budgetAccount}</td>
                <td style="text-align: right;">${formatCurrency(r.amount)}</td>
              </tr>
            `
              )
              .join('')}
          </tbody>
        </table>

        <p class="total">Total: ${formatCurrency(submission.totalAmount)}</p>

        <p style="margin-top: 24px; color: #6b7280;">
          Please see the attached PDF for the complete check request form.
        </p>
      </div>
      <div class="footer">
        <p>This email was automatically generated by the PTA Reimbursement System.</p>
      </div>
    </body>
    </html>
  `;
}

function generateConfirmationHTML(
  submission: EmailParams['submission'],
  requester: EmailParams['requester']
): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; }
        .header { background: #059669; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { padding: 24px; background: #fff; border: 1px solid #e5e7eb; border-top: none; }
        .total { font-size: 18px; font-weight: bold; margin-top: 16px; }
        .footer { text-align: center; padding: 16px; color: #6b7280; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 style="margin: 0; font-size: 24px;">Request Received</h1>
      </div>
      <div class="content">
        <p>Hi ${requester.payableTo},</p>

        <p>Your check request has been successfully submitted.</p>

        <p><strong>Reference ID:</strong> ${submission.id}</p>
        <p class="total">Total Amount: ${formatCurrency(submission.totalAmount)}</p>

        <p style="margin-top: 24px;">
          You will be notified once your request has been reviewed. Please keep the attached PDF for your records.
        </p>

        <p>Thank you!</p>
      </div>
      <div class="footer">
        <p>This email was automatically generated by the PTA Reimbursement System.</p>
      </div>
    </body>
    </html>
  `;
}

export async function sendNotificationEmail(params: EmailParams): Promise<void> {
  const { submission, requester, receipts, pdfBuffer, notificationEmail, resendApiKey } = params;

  const resend = new Resend(resendApiKey);

  // Convert Uint8Array to base64
  const pdfBase64 = Buffer.from(pdfBuffer).toString('base64');

  // Send notification to PTA
  await resend.emails.send({
    from: 'PTA Reimbursement <noreply@resend.dev>',
    to: [notificationEmail],
    replyTo: requester.email,
    subject: `New Check Request from ${requester.payableTo} - ${formatCurrency(submission.totalAmount)}`,
    html: generateEmailHTML(submission, requester, receipts),
    attachments: [
      {
        filename: `check-request-${submission.id}.pdf`,
        content: pdfBase64,
      },
    ],
  });

  // Send confirmation to requester
  await resend.emails.send({
    from: 'PTA Reimbursement <noreply@resend.dev>',
    to: [requester.email],
    subject: 'Your Check Request Has Been Received',
    html: generateConfirmationHTML(submission, requester),
    attachments: [
      {
        filename: `check-request-${submission.id}.pdf`,
        content: pdfBase64,
      },
    ],
  });
}
