import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("./routes/home.tsx"),
  route("about", "./routes/about.tsx"),
  route("news", "./routes/news.tsx"),
  route("events", "./routes/events.tsx"),
  route("get-involved", "./routes/get-involved.tsx"),
  route("programs", "./routes/programs.tsx"),
  route("parents", "./routes/parents.tsx"),
  route("sponsors", "./routes/sponsors.tsx"),
  route("contact", "./routes/contact.tsx"),
  route("dev/sync-calendar", "./routes/dev.sync-calendar.tsx"),
  route("reimbursement", "./routes/reimbursement.tsx"),
  route("pay-me", "./routes/pay-me.tsx"),
  route("reimbursement/success", "./routes/reimbursement.success.tsx"),
  route("api/reimbursement/submit", "./routes/api.reimbursement.submit.ts"),
  route("api/reimbursement/upload-presign", "./routes/api.reimbursement.upload-presign.ts"),
  route("api/reimbursement/upload-mock", "./routes/api.reimbursement.upload-mock.ts"),
  route("api/reimbursement/pdf", "./routes/api.reimbursement.pdf.ts"),
  route("api/reimbursement/convert-receipt", "./routes/api.reimbursement.convert-receipt.ts"),
  route("api/reimbursement/file", "./routes/api.reimbursement.file.ts"),
  route("admin/login", "./routes/admin.login.tsx"),
  route("admin", "./routes/admin.reimbursements.tsx", { id: "admin-index" }),
  route("admin/reimbursements", "./routes/admin.reimbursements.tsx"),
  route("admin/reimbursements/:id", "./routes/admin.reimbursement-detail.tsx"),
  route("api/admin/reimbursements/export", "./routes/api.admin.reimbursements-export.ts"),
  route("api/admin/reimbursements/file", "./routes/api.admin.reimbursement-file.ts"),
  route("api/admin/bulk-status", "./routes/api.admin.bulk-status.ts"),
  route("api/admin/bulk-delete", "./routes/api.admin.bulk-delete.ts"),
  route("api/admin/reimbursements/:id/status", "./routes/api.admin.reimbursement-status.ts"),
  route("api/admin/reimbursements/:id/delete", "./routes/api.admin.reimbursement-delete.ts"),
  route("api/subscribe", "./routes/api.subscribe.ts"),
  route("api/auth/google", "./routes/api.auth.google.ts"),
  route("api/auth/callback", "./routes/api.auth.callback.ts"),
  route("api/auth/logout", "./routes/api.auth.logout.ts"),
] satisfies RouteConfig;
