import {index, type RouteConfig, route} from '@react-router/dev/routes';

export default [
  index('./routes/home.tsx'),
  route('about', './routes/about.tsx'),
  route('news', './routes/news.tsx'),
  route('events', './routes/events.tsx'),
  route('get-involved', './routes/get-involved.tsx'),
  route('programs', './routes/programs.tsx'),
  route('parents', './routes/parents.tsx'),
  route('sponsors', './routes/sponsors.tsx'),
  route('archive', './routes/archive.tsx'),
  route('budget', './routes/budget.tsx'),
  route('api/archive/file', './routes/api.archive.file.ts'),
  route('contact', './routes/contact.tsx'),
  route('dev/sync-calendar', './routes/dev.sync-calendar.tsx'),
  route('reimbursement', './routes/reimbursement.tsx'),
  route('pay-me', './routes/pay-me.tsx'),
  route('reimbursement/success', './routes/reimbursement.success.tsx'),
  route('api/reimbursement/submit', './routes/api.reimbursement.submit.ts'),
  route('api/reimbursement/upload-presign', './routes/api.reimbursement.upload-presign.ts'),
  route('api/reimbursement/upload-mock', './routes/api.reimbursement.upload-mock.ts'),
  route('api/reimbursement/pdf', './routes/api.reimbursement.pdf.ts'),
  route('api/reimbursement/convert-receipt', './routes/api.reimbursement.convert-receipt.ts'),
  route('api/reimbursement/suggest-budget', './routes/api.reimbursement.suggest-budget.ts'),
  route('api/reimbursement/file', './routes/api.reimbursement.file.ts'),
  route('admin/login', './routes/admin.login.tsx'),
  route('admin', './routes/admin.reimbursements.tsx', {id: 'admin-index'}),
  route('admin/reimbursements', './routes/admin.reimbursements.tsx'),
  route('admin/reimbursements/:id', './routes/admin.reimbursement-detail.tsx'),
  route('api/admin/reimbursements/export', './routes/api.admin.reimbursements-export.ts'),
  route('api/admin/reimbursements/file', './routes/api.admin.reimbursement-file.ts'),
  route('api/admin/reimbursements/r2-cleanup', './routes/api.admin.reimbursement-r2-cleanup.ts'),
  route('api/admin/bulk-status', './routes/api.admin.bulk-status.ts'),
  route('api/admin/bulk-delete', './routes/api.admin.bulk-delete.ts'),
  route('api/admin/bulk-download', './routes/api.admin.bulk-download.ts'),
  route('api/admin/reimbursements/:id/contact', './routes/api.admin.reimbursement-contact.ts'),
  route(
    'api/admin/reimbursements/:id/attachments/:attachmentId',
    './routes/api.admin.reimbursement-attachment-delete.ts',
  ),
  route(
    'api/admin/reimbursements/:id/treasurer-fields',
    './routes/api.admin.reimbursement-treasurer-fields.ts',
  ),
  route(
    'api/admin/reimbursements/:id/pdf/regenerate',
    './routes/api.admin.reimbursement-pdf-regenerate.ts',
  ),
  route('api/admin/reimbursements/:id/pdf', './routes/api.admin.reimbursement-pdf-delete.ts'),
  route('api/admin/reimbursements/:id/receipts/:receiptId', './routes/api.admin.reimbursement-receipt-delete.ts'),
  route(
    'api/admin/reimbursements/:id/cash-check-nudge',
    './routes/api.admin.reimbursement-cash-check-nudge.ts',
  ),
  route('api/admin/reimbursements/:id/status', './routes/api.admin.reimbursement-status.ts'),
  route('api/admin/reimbursements/:id/delete', './routes/api.admin.reimbursement-delete.ts'),
  route('api/admin/reimbursements/:id/upload', './routes/api.admin.reimbursement-upload.ts'),
  route('privacy', './routes/privacy.tsx'),
  route('terms', './routes/terms.tsx'),
  route('api/subscribe', './routes/api.subscribe.ts'),
  route('api/auth/google', './routes/api.auth.google.ts'),
  route('api/auth/callback', './routes/api.auth.callback.ts'),
  route('api/auth/logout', './routes/api.auth.logout.ts'),
] satisfies RouteConfig;
