// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/events": {
    params: {};
  };
  "/get-involved": {
    params: {};
  };
  "/programs": {
    params: {};
  };
  "/parents": {
    params: {};
  };
  "/sponsors": {
    params: {};
  };
  "/archive": {
    params: {};
  };
  "/api/archive/file": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/dev/sync-calendar": {
    params: {};
  };
  "/reimbursement": {
    params: {};
  };
  "/pay-me": {
    params: {};
  };
  "/reimbursement/success": {
    params: {};
  };
  "/api/reimbursement/submit": {
    params: {};
  };
  "/api/reimbursement/upload-presign": {
    params: {};
  };
  "/api/reimbursement/upload-mock": {
    params: {};
  };
  "/api/reimbursement/pdf": {
    params: {};
  };
  "/api/reimbursement/convert-receipt": {
    params: {};
  };
  "/api/reimbursement/file": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/reimbursements": {
    params: {};
  };
  "/admin/reimbursements/:id": {
    params: {
      "id": string;
    };
  };
  "/api/admin/reimbursements/export": {
    params: {};
  };
  "/api/admin/reimbursements/file": {
    params: {};
  };
  "/api/admin/bulk-status": {
    params: {};
  };
  "/api/admin/bulk-delete": {
    params: {};
  };
  "/api/admin/reimbursements/:id/status": {
    params: {
      "id": string;
    };
  };
  "/api/admin/reimbursements/:id/delete": {
    params: {
      "id": string;
    };
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/api/subscribe": {
    params: {};
  };
  "/api/auth/google": {
    params: {};
  };
  "/api/auth/callback": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/news" | "/events" | "/get-involved" | "/programs" | "/parents" | "/sponsors" | "/archive" | "/api/archive/file" | "/contact" | "/dev/sync-calendar" | "/reimbursement" | "/pay-me" | "/reimbursement/success" | "/api/reimbursement/submit" | "/api/reimbursement/upload-presign" | "/api/reimbursement/upload-mock" | "/api/reimbursement/pdf" | "/api/reimbursement/convert-receipt" | "/api/reimbursement/file" | "/admin/login" | "/admin" | "/admin/reimbursements" | "/admin/reimbursements/:id" | "/api/admin/reimbursements/export" | "/api/admin/reimbursements/file" | "/api/admin/bulk-status" | "/api/admin/bulk-delete" | "/api/admin/reimbursements/:id/status" | "/api/admin/reimbursements/:id/delete" | "/privacy" | "/terms" | "/api/subscribe" | "/api/auth/google" | "/api/auth/callback" | "/api/auth/logout";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "./routes/events.tsx": {
    id: "routes/events";
    page: "/events";
  };
  "./routes/get-involved.tsx": {
    id: "routes/get-involved";
    page: "/get-involved";
  };
  "./routes/programs.tsx": {
    id: "routes/programs";
    page: "/programs";
  };
  "./routes/parents.tsx": {
    id: "routes/parents";
    page: "/parents";
  };
  "./routes/sponsors.tsx": {
    id: "routes/sponsors";
    page: "/sponsors";
  };
  "./routes/archive.tsx": {
    id: "routes/archive";
    page: "/archive";
  };
  "./routes/api.archive.file.ts": {
    id: "routes/api.archive.file";
    page: "/api/archive/file";
  };
  "./routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "./routes/dev.sync-calendar.tsx": {
    id: "routes/dev.sync-calendar";
    page: "/dev/sync-calendar";
  };
  "./routes/reimbursement.tsx": {
    id: "routes/reimbursement";
    page: "/reimbursement";
  };
  "./routes/pay-me.tsx": {
    id: "routes/pay-me";
    page: "/pay-me";
  };
  "./routes/reimbursement.success.tsx": {
    id: "routes/reimbursement.success";
    page: "/reimbursement/success";
  };
  "./routes/api.reimbursement.submit.ts": {
    id: "routes/api.reimbursement.submit";
    page: "/api/reimbursement/submit";
  };
  "./routes/api.reimbursement.upload-presign.ts": {
    id: "routes/api.reimbursement.upload-presign";
    page: "/api/reimbursement/upload-presign";
  };
  "./routes/api.reimbursement.upload-mock.ts": {
    id: "routes/api.reimbursement.upload-mock";
    page: "/api/reimbursement/upload-mock";
  };
  "./routes/api.reimbursement.pdf.ts": {
    id: "routes/api.reimbursement.pdf";
    page: "/api/reimbursement/pdf";
  };
  "./routes/api.reimbursement.convert-receipt.ts": {
    id: "routes/api.reimbursement.convert-receipt";
    page: "/api/reimbursement/convert-receipt";
  };
  "./routes/api.reimbursement.file.ts": {
    id: "routes/api.reimbursement.file";
    page: "/api/reimbursement/file";
  };
  "./routes/admin.login.tsx": {
    id: "routes/admin.login";
    page: "/admin/login";
  };
  "./routes/admin.reimbursements.tsx": {
    id: "admin-index";
    page: "/admin";
  } | {
    id: "routes/admin.reimbursements";
    page: "/admin/reimbursements";
  };
  "./routes/admin.reimbursement-detail.tsx": {
    id: "routes/admin.reimbursement-detail";
    page: "/admin/reimbursements/:id";
  };
  "./routes/api.admin.reimbursements-export.ts": {
    id: "routes/api.admin.reimbursements-export";
    page: "/api/admin/reimbursements/export";
  };
  "./routes/api.admin.reimbursement-file.ts": {
    id: "routes/api.admin.reimbursement-file";
    page: "/api/admin/reimbursements/file";
  };
  "./routes/api.admin.bulk-status.ts": {
    id: "routes/api.admin.bulk-status";
    page: "/api/admin/bulk-status";
  };
  "./routes/api.admin.bulk-delete.ts": {
    id: "routes/api.admin.bulk-delete";
    page: "/api/admin/bulk-delete";
  };
  "./routes/api.admin.reimbursement-status.ts": {
    id: "routes/api.admin.reimbursement-status";
    page: "/api/admin/reimbursements/:id/status";
  };
  "./routes/api.admin.reimbursement-delete.ts": {
    id: "routes/api.admin.reimbursement-delete";
    page: "/api/admin/reimbursements/:id/delete";
  };
  "./routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "./routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "./routes/api.subscribe.ts": {
    id: "routes/api.subscribe";
    page: "/api/subscribe";
  };
  "./routes/api.auth.google.ts": {
    id: "routes/api.auth.google";
    page: "/api/auth/google";
  };
  "./routes/api.auth.callback.ts": {
    id: "routes/api.auth.callback";
    page: "/api/auth/callback";
  };
  "./routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/about": typeof import("./app/./routes/about.tsx");
  "routes/news": typeof import("./app/./routes/news.tsx");
  "routes/events": typeof import("./app/./routes/events.tsx");
  "routes/get-involved": typeof import("./app/./routes/get-involved.tsx");
  "routes/programs": typeof import("./app/./routes/programs.tsx");
  "routes/parents": typeof import("./app/./routes/parents.tsx");
  "routes/sponsors": typeof import("./app/./routes/sponsors.tsx");
  "routes/archive": typeof import("./app/./routes/archive.tsx");
  "routes/api.archive.file": typeof import("./app/./routes/api.archive.file.ts");
  "routes/contact": typeof import("./app/./routes/contact.tsx");
  "routes/dev.sync-calendar": typeof import("./app/./routes/dev.sync-calendar.tsx");
  "routes/reimbursement": typeof import("./app/./routes/reimbursement.tsx");
  "routes/pay-me": typeof import("./app/./routes/pay-me.tsx");
  "routes/reimbursement.success": typeof import("./app/./routes/reimbursement.success.tsx");
  "routes/api.reimbursement.submit": typeof import("./app/./routes/api.reimbursement.submit.ts");
  "routes/api.reimbursement.upload-presign": typeof import("./app/./routes/api.reimbursement.upload-presign.ts");
  "routes/api.reimbursement.upload-mock": typeof import("./app/./routes/api.reimbursement.upload-mock.ts");
  "routes/api.reimbursement.pdf": typeof import("./app/./routes/api.reimbursement.pdf.ts");
  "routes/api.reimbursement.convert-receipt": typeof import("./app/./routes/api.reimbursement.convert-receipt.ts");
  "routes/api.reimbursement.file": typeof import("./app/./routes/api.reimbursement.file.ts");
  "routes/admin.login": typeof import("./app/./routes/admin.login.tsx");
  "admin-index": typeof import("./app/./routes/admin.reimbursements.tsx");
  "routes/admin.reimbursements": typeof import("./app/./routes/admin.reimbursements.tsx");
  "routes/admin.reimbursement-detail": typeof import("./app/./routes/admin.reimbursement-detail.tsx");
  "routes/api.admin.reimbursements-export": typeof import("./app/./routes/api.admin.reimbursements-export.ts");
  "routes/api.admin.reimbursement-file": typeof import("./app/./routes/api.admin.reimbursement-file.ts");
  "routes/api.admin.bulk-status": typeof import("./app/./routes/api.admin.bulk-status.ts");
  "routes/api.admin.bulk-delete": typeof import("./app/./routes/api.admin.bulk-delete.ts");
  "routes/api.admin.reimbursement-status": typeof import("./app/./routes/api.admin.reimbursement-status.ts");
  "routes/api.admin.reimbursement-delete": typeof import("./app/./routes/api.admin.reimbursement-delete.ts");
  "routes/privacy": typeof import("./app/./routes/privacy.tsx");
  "routes/terms": typeof import("./app/./routes/terms.tsx");
  "routes/api.subscribe": typeof import("./app/./routes/api.subscribe.ts");
  "routes/api.auth.google": typeof import("./app/./routes/api.auth.google.ts");
  "routes/api.auth.callback": typeof import("./app/./routes/api.auth.callback.ts");
  "routes/api.auth.logout": typeof import("./app/./routes/api.auth.logout.ts");
};